/**
 * Type declarations for the WASM module generated by wasm-pack
 * These types match the Rust API in wasm/src/bindings.rs
 */

declare module '../../public/wasm/crochet_pattern_wasm.js' {
  // Initialize the WASM module
  export default function init(): Promise<void>;

  // Load and validate a GLTF/GLB file
  export function load_model(data: Uint8Array): Promise<{
    vertexCount: number;
    faceCount: number;
    boundingBox: {
      min: { x: number; y: number; z: number };
      max: { x: number; y: number; z: number };
    };
    surfaceArea: number;
    isManifold: boolean;
    hasUVs: boolean;
    hasNormals: boolean;
  }>;

  // Generate a complete crochet pattern
  export function generate_pattern(
    modelData: Uint8Array,
    config: {
      stitches_per_inch: number;
      rows_per_inch: number;
      yarn_weight: string;
      hook_size_mm: number;
      target_width_inches?: number;
      target_height_inches?: number;
      construction_type: string;
      max_distortion: number;
      simplify_mesh: boolean;
      target_stitch_count?: number;
    }
  ): Promise<any>;

  // Validate a model
  export function validate_model(data: Uint8Array): Promise<{
    valid: boolean;
    errors: string[];
    warnings: string[];
  }>;

  // Get mesh statistics
  export function get_mesh_info(data: Uint8Array): Promise<{
    vertexCount: number;
    faceCount: number;
    boundingBox: {
      min: { x: number; y: number; z: number };
      max: { x: number; y: number; z: number };
    };
    surfaceArea: number;
    isManifold: boolean;
    hasUVs: boolean;
    hasNormals: boolean;
  }>;

  // Export pattern in various formats
  export function export_pattern(pattern: any, format: string): Promise<string>;
}
